openapi: 3.0.3
info:
  title: rails openapi template
  version: '1.0'
servers:
  - url: 'http://localhost:3000/v1'
    description: development server
paths:
  '/tasks':
    get:
      summary: Get task list
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              examples:
                Get Example:
                  value:
                    - id: 142
                      description: buy apple
                      completed: false
                      created_at: '2022-05-07T21:32:28Z'
                      user_id: 3
  '/tasks/{taskId}':
    parameters:
      - schema:
          type: integer
        name: taskId
        in: path
        required: true
        description: Id of an existing task.
    get:
      summary: Get Task Info by Task ID
      tags: []
      responses:
        '200':
          description: task found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                Get task 142:
                  value:
                    id: 142
                    description: buy apple
                    completed: false
                    created_at: '2022-05-07T21:32:28Z'
                    user_id: 3
        '404':
          description: not found
      operationId: get-tasks-taskId
      description: Retrieve the information of the task with the matching task ID.
components:
  schemas:
    Task:
      title: Task
      type: object
      description: 'This model represents a todo task.'
      examples:
        - id: 142
          description: buy apple
          completed: false
          created_at: '2022-05-07T21:32:28Z'
          user_id: 3
      properties:
        id:
          type: integer
          description: primary id
          minimum: 1
        description:
          type: string
        completed:
          type: boolean
        created_at:
          type: string
          format: date-time
        user_id:
          type: integer
          minimum: 1
      required:
        - description
